### ISSUE TITLE
failed to deploy

### ISSUE THREAD

**Issue by koaning** [rohanshiva/Deta-FastAPI-JWT-Auth-Blog#1]
When I run `deta new` an error appears. 

```
> deta new
Error: failed to deploy: Improper file name venv/lib/python3.7/site-packages/setuptools/script (dev).tmpl. See naming rules
```

Is that supposed to happen?

**Comment by rohanshiva** [comment]
Can you please try providing a name? For more info refer to https://docs.deta.sh/docs/cli/commands/#deta-auth-create-api-key

**Comment by koaning** [comment]
The issue here was that my virtualenv was called `venv`. It seems deta assumes it's called `.venv`.
